### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by amcmaster4** [SneezingCactus/manifold-server#3]
Each time I try to start a server, I get this error:

> manifold-server@1.1.0 start
> tsx index.ts

/home/deck/Downloads/manifold-server-master/node_modules/.bin/tsx: line 1: ../tsx/dist/cli.mjs: No such file or directory

I am on a Steam Deck.

**Comment by SneezingCactus** [comment]
Have you installed the server's dependencies with `npm install` before trying to open the server?

**Comment by amcmaster4** [comment]
Yes. I was following the tutorial. Is it possible that it's because I'm using nvm to install node js?

**Comment by SneezingCactus** [comment]
That could be it. I had issues running the server from the bash script because I had two versions of Node in my computer: Node v12 installed using apt, and Node v20 installed using nvm. When I open the bash script by itself (without opening a terminal beforehand), it uses Node v12 and immediately crashes because the code makes heavy use of ES6, but if I open the server from a terminal (by doing `npm run start`), it uses Node v20 and everything works perfectly. You should try the latter, maybe you're running into a similar issue.
